logging:
  level:
    com.abdullah.home.automation: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  thymeleaf.cache: false
  # ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
  datasource:
    url: jdbc:mysql://localhost:3306/ha?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: rootcm
    testWhileIdle: true
    validationQuery: SELECT 1
    datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      id:
        new_generator_mappings: false

  thymeleaf:
    cache: false


  # ===============================
  # = MAIL CONFIG
  # ===============================
  mail:
    host: smtp.gmail.com
    username: a.kyium.khan@gmail.com
    password: 00
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false


support:
  email: a.kyium.khan@gmail.com

mail:
  smtp:
    starttls:
      enable: true
  host: smtp.gmail.com
  
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  info:
    git:
      mode: full

  auditevents:
    enabled: true

#  trace:
#    http:
#      enabled: true
#
## INFO ENDPOINT CONFIGURATION
#info:
#  app:
#    name: @project.name@
#    description: @project.description@
#    version: @project.version@
#    encoding: @project.build.sourceEncoding@
#    java:
#      version: @java.version@
regulator:
  mode: VoltageRegulatorFinalShape
#  mode: Regulator2

hardware:
  hardwareMode: without-hardware

  #without-hardware
  #with-hardware
  # mvn spring-boot:run -Dspring-boot.run.arguments="--hardware.hardwareMode=without-hardware --hardware.hardwareMode=VoltageRegulatorFinalShape"
meteostat:
  baseUrl: https://api.meteostat.net/v1/history/hourly?station=
  apiKey: qcca1JKR